# Physical Infrastructure {#physical}

This section is all about the physical space & time needed to host an unconf. 

## Where is your unconf? {-}

First things first, you need a space. The space should be the first thing you acquire, because without a space, you cannot have an unconf. This should be a space large enough for your conference, typically 30-50 people. There should be working space for all participants: chairs, table surface, whiteboard & dry erase markers, paper & pens. The location should also have strong WiFi that everyone can access and plenty of electrical outlets for charging laptops. See Chapter \@ref(people) for more details about what your space should have. 

Some ideas for unconf spaces are: 

- Large meeting rooms or classrooms at academic institutions 
- Co-working spaces
- Meeting rooms that your employer can rent out or donate to you for two to three days 

Ideally, the space should be within walking distance of one or more hotels so that your participants can easily go to and fro. If your location is not near lodging, rent a van that can shuttle participant from the hotel to the venue, or consider asking participants to carpool between the venue and the hotel(s). 

When you check out the space, make sure that you know where the dumpsters are. You'll need to take out the trash! `r emo::ji("recycling symbol")`

You should have the space secured at least 4-6 months ahead of time. 

## When is your unconf? {-}

Date considerations: 

- Weekends are optimal for people whose jobs wouldn't allow for them to attend this type of event during the week. However, you will also be asking folks to give up one of their weekends. 
- Weekdays require people to take time off of work, but they may be able to get their employer to fund their travel and lodging. There are also weekday obligations, such as getting children to and from school, that may limit some participants' ability to fully participate. 
- Do your best to avoid major religious holidays. Consult the [interfaith calendar](http://www.interfaith-calendar.org). 
- If you are hosting in the US or Canada on a weekend, avoid daylight savings time so that people aren't losing an hour of sleep! `r emo::ji("sleeping face")`

## Where will people stay? {-}

Try to secure a block of rooms at a nearby hotel at least two months before your event. It's much easier to release a few rooms later on than it is to create new hotels rooms out of nothing! 