---
title: "How to Organize an R Unconference"
author: "Angela Li, Sam Tyner"
documentclass: "book"
site: bookdown::bookdown_site
---

# Preface {-}

This guide came to be at the [Chicago R Unconference](https://chirunconf.github.io/), March 9-10, 2019. Many of the principles can be applied to any type of unconf, but our experience has been in attending [rOpenSci]() unconferences and in hosting our own unconferences, the [Chicago R Unconference](https://chirunconf.github.io/) and the [Uncoast Unconference](http://uuconf.rbind.io/). 

<!--Hi, Sam here. Just writing an outline for now. --> 

1. What is an unconf and why should you organize one? 
2. What **physical** infrastructure do you need to host an unconference?
3. What **online** infrastructure do you need to host an unconference? 
4. `r emo::ji("music")` Money money money money. MON-AY `r emo::ji("music")`
5. Applications: what questions to ask, how to evalues them, and what tools to use
6. Taking care of people: pre-unconf chats, food, logding, travel, space accomodations
7. Day One: intros/icebreakers, projects, space utilization, issue tracking
8. Day Two: continuing/switching projects, "finishing" projects, reporting out
9. After the unconf



